### PR TITLE
Update MenuList.tsx

### PR DESCRIPTION
**Pull request by BooYeu**
Fix ref doesn't update when navigate pages

### CODE REVIEW

**Review by markmccoid — COMMENTED** [review]
I have implemented this change and it fixed my issue with the onPress functions never changing.

**Comment by enesozturk** [comment]
Hi @BooYeu, it's been a long time, I could not check my packages, good to see you again for a contribution. But I need more explanation about the changes to understand this value, why did we need this?

**Comment by BooYeu** [comment]
ok~~Thank you for reply! ^_^

**Comment by enesozturk** [comment]
I think it would be better to keep it open, I will check it. If it's solving issues, we might merge it.

**Comment by enesozturk** [comment]
Hi @BooYeu, long time no check. I tried the changes on the local but as I mentioned earlier, making these changes triggers the state every time you open the menu. This may affect the performance unexpectedly. Also couldn't understand the problem @markmccoid pointed out. If you guys think there are still issues, feel free to open PR again. Closing it for now. Thanks!

**Pull request closed without merging**
