### PR TITLE
Update useDeviceOrientation.ts

### PR DESCRIPTION
**Pull request by BooYeu**
Use remove function instead of removeEventListener

### CODE REVIEW

**Comment by enesozturk** [comment]
Hi @BooYeu, I know it's been a long time. Thank you for your contribution! Just wanted to know what is the benefit of this usage? Is it prevents some bugs?

**Comment by BooYeu** [comment]
removeEventListener is not recommended by react-native group. It shows warn now and may be removed in the future~~

**Comment by enesozturk** [comment]
I see, that is great, thanks!

**Comment by enesozturk** [comment]
In line 13. I did not invoke `getWindowOrientation` function 🤦🏻‍♂️ Looks like it is a mistake. And also wanted to discuss could we use [`useWindowDimensions`](https://reactnative.dev/docs/usewindowdimensions) hook here to clarify this custom hook? Would be good. I will try to add it.

**Review by enesozturk — APPROVED** [review]

**Comment by enesozturk** [comment]
Merged. Thanks!

**Pull request merged**
