### PR TITLE
fix: mark onPress as optional

### PR DESCRIPTION
**Pull request by zhigang1992**

### CODE REVIEW

**Comment by enesozturk** [comment]
Hi @zhigang1992, thanks for your contribution 🙌🏽 What was your motivation behind this? What kind of usage are you trying to do?

**Comment by zhigang1992** [comment]
For example, the `asTitle` version does not have a `onPress` event?

**Comment by enesozturk** [comment]
Oh I see, actually I think I already implement this but not remember. Will check it 👍🏽

**Comment by enesozturk** [comment]
This is already implemented [here](https://github.com/enesozturk/react-native-hold-menu/commit/080d18e8b3b388c93f4e08be12db53a5f4e2c01e) and will be available in next release. Thanks anyway 🙌🏽

**Pull request closed without merging**
